/**
 * Emits SQL assertions comparing the TypeScript key derivation against the
 * Postgres one, on stdout. scripts/db/verify.sh pipes it into psql.
 *
 * This matters more than it looks. canonicalize() computes title_key in
 * TypeScript and hands it to public.resolve_book(), which compares it against a
 * generated column computed in SQL. If the two implementations ever disagree —
 * on an accent, on a leading article, on punctuation — resolution does not
 * error. It silently stops matching, every listing mints a fresh node, and the
 * graph quietly stops finding cycles. So: same inputs, both implementations,
 * asserted equal.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { slugify, surnameOf, titleKey } from '../../lib/canonicalize/slug';

const SEED = join(import.meta.dirname, '..', '..', 'supabase', 'seed.sql');

/** Awkward on purpose: accents, ligatures, articles, punctuation, case. */
const TRICKY = [
  'The Norton Anthology of American Literature, Volume B',
  "Gray's Anatomy for Students",
  'Calculus: Early Transcendentals',
  'A Writer’s Reference',
  'An Introduction to Genetic Analysis',
  'Économie Politique',
  'Der Prozeß',
  'Æsthetics and Œuvre',
  'Naïve Set Theory',
  'Møller and Ångström',
  'Introducción a la Lingüística',
  '  spaced   out   title  ',
  'ALL CAPS TITLE',
  'Hyphen-Heavy — Title',
];

const TRICKY_AUTHORS = [
  'Junot Díaz',
  'Émile Durkheim',
  'Ludwig van Beethoven',
  'William Strunk Jr.',
  'J. J. Sakurai',
  'Robert T. Morrison',
  'Erwin Schrödinger',
  'Søren Kierkegaard',
  'Paul Erdős',
];

function sqlLiteral(text: string): string {
  return `'${text.replace(/'/g, "''")}'`;
}

/** Titles as the seed writes them, so real data is covered too. */
function seedTitles(): string[] {
  const sql = readFileSync(SEED, 'utf8');
  const books = sql.slice(sql.indexOf('insert into public.books'), sql.indexOf('-- --- copies'));
  return [...books.matchAll(/^\s{2}\('[a-z0-9-]+',\s+'[a-z0-9-]+',\s+'((?:[^']|'')*)'/gm)].map(
    ([, title]) => title.replace(/''/g, "'"),
  );
}

const lines: string[] = [
  '-- Generated by scripts/db/parity.ts. Not checked in.',
  'begin;',
];

for (const title of [...new Set([...TRICKY, ...seedTitles()])]) {
  lines.push(
    `select tests.eq(public.title_key(${sqlLiteral(title)}), ${sqlLiteral(titleKey(title))}, ` +
      `'title_key parity: ${title.replace(/'/g, "''").slice(0, 60)}');`,
  );
}

for (const author of TRICKY_AUTHORS) {
  lines.push(
    `select tests.eq(public.author_surnames(array[${sqlLiteral(author)}]), ` +
      `array[${sqlLiteral(surnameOf(author))}], ` +
      `'surname parity: ${author.replace(/'/g, "''")}');`,
  );
}

for (const text of [...TRICKY, ...TRICKY_AUTHORS]) {
  lines.push(
    `select tests.eq(public.slugify(${sqlLiteral(text)}), ${sqlLiteral(slugify(text))}, ` +
      `'slugify parity: ${text.replace(/'/g, "''").slice(0, 60)}');`,
  );
}

lines.push('rollback;');
process.stdout.write(lines.join('\n') + '\n');
